# Site settings
title: Freelancer - Jens de Rond
name: Jens de Rond
email: jensderond@gmail.com
url: https://jensderond.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "freelancer, developer, redkiwi, student, jens de rond, awesome, bacardi"
skills: "Developer - Student - Digital Creator @ Redkiwi"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 29C45B #18bc9c #80B3FF
  primary-rgb: "41,196,91" #"24,288,156" #"128,179,255"
  secondary: 282828 #2c3e50 #FD6E8A
  secondary-dark: 181818 #233140 #A2122F
  secondary-dark-rgba: "rgba(24,24,24,0.8)" #233140 #A2122F

# Footer settings
footer:
  copyright: Jens de Rond
  location: Location
  social: Around the Web
  contact: Contact

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/Jensderond
  - title: twitter
    url: https://twitter.com/Jensderond
  - title: facebook
    url: https://www.facebook.com/jens.derond
  - title: instagram
    url: https://instagram.com/Jensderond

# Postal address (add as many lines as necessary)
address:
  - line: Tholen, 4691DA
  - line: Netherlands

# Credits content
contact-info:
  phone: '<a href="tel:0031614609861">+31 - 6 14 60 98 61</a>'
  email: '<a href="mailto:jensderond@gmail.com">jensderond@gmail.com</a>'
# Build settings
markdown: kramdown
permalink: pretty

exclude: [node_modules, gulpfile.js, src, package.json, README.md, screenshot.png, package-lock.json]
